### ISSUE TITLE
Multiple simulator parameters and ratio estimator inference

### ISSUE THREAD

**Issue by fbkarsdorp** [montefiore-ai/hypothesis#5]
This is more of a question than an issue, and it might very well be too early to ask, since the package is still in alpha stage, but I was wondering whether the current implementation can be used for inferring multiple simulator parameters. All examples in the notebooks (which are very clear, btw!) seem to focus on the inference of a single parameter. 

Anyway, thanks a lot for what's starting to look like a really clean and interesting package!

**Comment by JoeriHermans** [comment]
Hi @fbkarsdorp 

Thanks for your comments! This depends on the technique you are using and what kind of (assuming Bayesian) posterior your want to infer. Can the parameters be concatenated into say `input = [theta_1, theta_2, theta_3]`? If not, I'll have to think about this a bit more clearly. Because this will also change how the training criterions are structured.

Joeri

**Comment by fbkarsdorp** [comment]
Hi @JoeriHermans, 

Thanks! Yes, the parameters can be concatenated into some array-like structure. I'm trying some experiments with a simple extension of the wright-fisher model, which is typically used for modelling genetic drift. In my extension, I have at least two parameters, one controlling the probability of mutation, and one controlling the influence of frequency effects (either positive or negative).

**Comment by JoeriHermans** [comment]
Oh in that case concatenating them should indeed be fine! Let me know if you run into issues. Happy to help.

Joeri

**Comment by fbkarsdorp** [comment]
OK. Thanks! Training the ratio estimator seems to work, but I'm running into issues with the `AALRMetropolisHastings` inference. Is this the best place to ask questions?

**Comment by JoeriHermans** [comment]
Sure, best to keep a public record :) However, I would suggest the following. Since your parameter space is low-dimensional, I think scanning is a better strategy. You won't have issues with auto-correlation, and tuning the MCMC chain (which can be quite annoying imho). So I'm suggesting to making some kind of 2D heatmap, where you scan over the values and use the ratio estimator to extract the (log) posterior probabilities.

**Comment by fbkarsdorp** [comment]
I'm gonna look the scanning strategy. That's similar to what you propose in https://github.com/montefiore-ai/hypothesis/blob/master/examples/markov-chain-monte-carlo/aalr_metropolis_hastings.ipynb, am I right?

I haven't looked at the boilerplate script. Currently just adapting the aalr_metropolis_hastings.ipynb notebook.

**Comment by fbkarsdorp** [comment]
There's probably some silly thing I'm doing wrong. Here's a gist of the notebook I'm working on: https://gist.github.com/fbkarsdorp/61f778dab25c0828e33fc4825ec7d4a9 

I don't want to take up too much of your time, but perhaps you spot the problem after a quick glance.

**Comment by JoeriHermans** [comment]
I think this looks OK?

So your heatmap is the posterior right? Would be good to test if you get a similar result with larger architectures (e.g., increase number of layers and dimensionality of the hidden layers). Doesn't seem to me that the model has converged yet, so I would let it train for a bit longer.

A good test would be to generate several mock simulations and test if the posterior actually captures those. The corner plot in the end doesn't show the posterior though, just the obtained log probabilities.

Joeri

**Comment by fbkarsdorp** [comment]
Thanks for your advice! I've updated the gist notebook, and it appears to be doing an excellent job in recovering the parameters. 

Btw, if you're interested, I'm willing to make a PR for a notebook sketching the multiple simulator parameters scenario.

**Comment by JoeriHermans** [comment]
Sure, contributions are always welcome :) Feel free to open a PR, we'll iterate over it.

Feel free to open an issue again if you have a question.

**Comment by fbkarsdorp** [comment]
Hi @JoeriHermans, although this issue is closed, I figured this might still be the best place to ask a follow-up question. 

With more parameters than 2, the parameters search strategy becomes less feasible, so I was looking at the `AALRMetropolisHastings` class for doing inference. Everything seemed to be working OK, until I pulled some of your recent changes. It appears that the changes in https://github.com/montefiore-ai/hypothesis/commit/2c59a90b969b99d8691568fb8b57e4606d9312f9 are the problem, making the code unsuitable for doing inference for more than 1 parameter. L161 expects the acceptance ratio to be a single value, but this is not the case when working with multiple parameters:

The https://github.com/montefiore-ai/hypothesis/blob/1b75acfe36ae75b495ed6317dd752c8f15427e64/hypothesis/inference/mcmc.py#L161

Happy to provide a more detailed example if you need more details.

**Comment by JoeriHermans** [comment]
Hi @fbkarsdorp 

Are you using a `torch.distributions.uniform.Uniform` prior? That might be the cause because the `log_prob` operation there gives a log probability for every dimension.

Joeri

**Comment by fbkarsdorp** [comment]
I am, yes. Is there another class I should use instead?

**Comment by JoeriHermans** [comment]
Yeah, I've also encounter this problem. The most "elegant" way I came up with (maybe you have a better idea) is to create a kind of a wrapper class:

```python
class MyPrior:

    def __init__(self, prior):
        self.prior = prior

    def log_prob(self, inputs):
        return self.prior.log_prob(inputs).sum()
```
The problem is that the `log_prob` API of the uniform distribution (in PyTorch) varies from the other classes, as they only output a singular value. So yeah, sorry about that :/

**Comment by fbkarsdorp** [comment]
I see! OK. That makes sense. Thanks!
